trigger:
- none

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: build
  jobs:
  - job: build_knative_serving
    variables:
      GOPATH: $(Agent.BuildDirectory)/go
      GOROOT:
      KNATIVE_SERVING_RELATIVE_PATH: go/src/knative.dev/serving
    steps:
    - checkout: self
      path: $(KNATIVE_SERVING_RELATIVE_PATH)
      displayName: Checkout branch '$(Build.SourceBranchName)'
    - bash: |
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo apt-get update
        sudo apt-get install golang-go
        echo "##vso[task.setvariable variable=PATH]${PATH}:$(GOPATH)/bin"
      displayName: 'Install deps'
    - bash: |
        cd $(Agent.BuildDirectory)/$(KNATIVE_SERVING_RELATIVE_PATH)
        go test ./...
      displayName: 'Run unit tests'
